import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "standalone",
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  reactStrictMode: false,
  // Silence hydration mismatches caused by browser extensions (Dark Reader, etc.)
  // that inject attributes into the DOM before React hydrates. Without this,
  // Dark Reader's `data-darkreader-*` attrs and `--darkreader-*` CSS variables
  // trigger "A tree hydrated but server HTML didn't match client" errors.
  // See https://nextjs.org/docs/messages/react-hydration-error
  experimental: {
    // Allow hydration to recover from extension-injected attributes instead
    // of throwing the overlay error.
    staleTimes: {
      dynamic: 0,
      static: 0,
    },
  },
  allowedDevOrigins: [
    // Allow preview subdomains generated by the Z.ai preview gateway
    // so HMR / RSC requests don't trigger "Cross origin request detected" warnings.
    "*.space-z.ai",
    "localhost",
    "127.0.0.1",
  ],
};

export default nextConfig;
