import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "standalone",

  // Don't expose the Next.js version via the `x-powered-by` response header.
  // (Defense in depth — `src/middleware.ts` also strips it.)
  poweredByHeader: false,

  // Strict mode catches unsafe lifecycle patterns in dev. The previous
  // setting of `false` was likely a workaround for double-rendering issues
  // in dev; in production builds strict mode has no runtime cost, and in
  // dev it surfaces real bugs (effect cleanup, stale state). Re-enabled.
  reactStrictMode: true,

  // FAIL THE BUILD on TypeScript errors. The previous `true` let type
  // errors ship to production silently — a critical risk because type
  // errors often mask real runtime bugs. If the build fails, fix the
  // type error; don't bypass it.
  typescript: {
    ignoreBuildErrors: false,
  },

  // Allow preview subdomains generated by the Z.ai preview gateway so HMR /
  // RSC requests don't trigger "Cross origin request detected" warnings.
  allowedDevOrigins: [
    "*.space-z.ai",
    "localhost",
    "127.0.0.1",
  ],

  // Security & caching headers applied to every response.
  // (Some of these are also set in `src/middleware.ts` — the redundancy is
  // intentional: middleware runs on dynamic routes, this runs on static
  // assets too.)
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(), browsing-topics=()",
          },
          { key: "X-DNS-Prefetch-Control", value: "off" },
        ],
      },
      // Static assets get long-lived cache + immutable hint (filename has
      // a content hash, so it's safe to cache forever).
      {
        source: "/_next/static/(.*)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
